-- begin CONFECTIONERY_TECHNOLOGICAL_MAP
create unique index IDX_CONFECTIONERY_TECHNOLOGICAL_MAP_UNIQ_NAME on CONFECTIONERY_TECHNOLOGICAL_MAP (NAME)^
-- end CONFECTIONERY_TECHNOLOGICAL_MAP
-- begin CONFECTIONERY_COMPONENT
create unique index IDX_CONFECTIONERY_COMPONENT_UNIQ_NAME on CONFECTIONERY_COMPONENT (NAME)^
-- end CONFECTIONERY_COMPONENT
-- begin CONFECTIONERY_TECHNOLOGICAL_MAP_COMPONENT_LINK
alter table CONFECTIONERY_TECHNOLOGICAL_MAP_COMPONENT_LINK add constraint FK_TECMAPCOM_ON_TECHNOLOGICAL_MAP foreign key (TECHNOLOGICAL_MAP_ID) references CONFECTIONERY_TECHNOLOGICAL_MAP(ID)^
alter table CONFECTIONERY_TECHNOLOGICAL_MAP_COMPONENT_LINK add constraint FK_TECMAPCOM_ON_COMPONENT foreign key (COMPONENT_ID) references CONFECTIONERY_COMPONENT(ID)^
-- end CONFECTIONERY_TECHNOLOGICAL_MAP_COMPONENT_LINK
